project:
  type: default

format:
  html:
    theme: 
      - cosmo
      - css/steampunk-SEMANTIC.scss
    css: 
      - css/custom-cards.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai
    mainfont: "Baskerville, Georgia, serif"
    fontsize: 1em
    linestretch: 1.6
    # Add these lines to activate the citation UI
    citation: true
    # This generates the 'How to cite' section at the bottom
    appendix-style: plain 
    # Optional: adds a hover preview for citations
    citation-hover: true

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

