project:
  type: default

format:
  html:
    theme: 
      - cosmo
      - css/steampunk-SEMANTIC.scss
    css: 
      - css/custom-cards.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai
    mainfont: "Baskerville, Georgia, serif"
    fontsize: 1em
    linestretch: 1.6

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

